version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
    - ./sql:/sql
    - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: .
    links:
      - postgres
    ports:
      - 8080:8080
#    command: ["./wait-for-it.sh", "postgres:5432"]



volumes:
  pgdata: