CREATE USER raise_user_test WITH PASSWORD 'admin';

-- GRANT SELECT, INSERT, UPDATE, DELETE ON DATABASE raise_db to raise_user;
\c raise_db_test
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO raise_user_test;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO raise_user_test;

-- REVOKE ALL PRIVILEGES ON DATABASE raise_db FROM raise_user;
-- REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM raise_user;
-- REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM raise_user;
-- REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM raise_user;
-- DROP USER raise_user