CREATE DATABASE raise_db;
--
-- create user raise_user with password 'hash25';
--
-- revoke connect on database raise_db from public;
--
-- grant connect on database raise_db to raise_user;
--
-- revoke all on all tables in schema public from raise_db;
--
-- grant select, insert, update, delete on all tables in schema public to raise_user;
